//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;


namespace Formula81.XrmToolBox.Libraries.Xrm {
    
    
    /// <summary>
    /// <para>Track changes to records for analysis, record keeping, and compliance.</para>
    /// <para>Display Name: Auditing</para>
    /// </summary>
    [EntityLogicalName("audit")]
    [DebuggerDisplay("{DebuggerDisplay,nq}")]
    [DataContract()]
    public partial class Audit : ExtendedEntity<EmptyEnum, EmptyEnum> {
        
        public const string EntityLogicalName = "audit";
        
        public const int EntityTypeCode = 4567;
        
        public Audit() : 
                base(EntityLogicalName) {
        }
        
        public Audit(Guid Id) : 
                base(EntityLogicalName, Id) {
        }
        
        private string DebuggerDisplay {
            get {
                return GetDebuggerDisplay(null);
            }
        }
        
        [AttributeLogicalName("auditid")]
        public override Guid Id {
            get {
                return base.Id;
            }
            set {
                SetId("auditid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the auditing instance</para>
        /// <para>Display Name: Record Id</para>
        /// </summary>
        [AttributeLogicalName("auditid")]
        [DisplayName("Record Id")]
        public Guid? AuditId {
            get {
                return GetAttributeValue<Guid?>("auditid");
            }
            set {
                SetId("auditid", value);
            }
        }
        
        /// <summary>
        /// <para>Actions the user can perform that cause a change</para>
        /// <para>Display Name: Event</para>
        /// </summary>
        [AttributeLogicalName("action")]
        [DisplayName("Event")]
        public Audit_Action? Action {
            get {
                return GetOptionSetValue<Audit_Action>("action");
            }
        }
        
        /// <summary>
        /// <para>Additional Info for Audit</para>
        /// <para>Display Name: Additional Info</para>
        /// </summary>
        [AttributeLogicalName("additionalinfo")]
        [DisplayName("Additional Info")]
        public string AdditionalInfo {
            get {
                return GetAttributeValue<string>("additionalinfo");
            }
            set {
                SetAttributeValue("additionalinfo", value);
            }
        }
        
        /// <summary>
        /// <para>Contains a CSV of the ColumnNumber metadata property of attributes</para>
        /// <para>Display Name: Changed Field</para>
        /// </summary>
        [AttributeLogicalName("attributemask")]
        [DisplayName("Changed Field")]
        public string AttributeMask {
            get {
                return GetAttributeValue<string>("attributemask");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the calling user in case of an impersonated call</para>
        /// <para>Display Name: Calling User</para>
        /// </summary>
        [AttributeLogicalName("callinguserid")]
        [DisplayName("Calling User")]
        public EntityReference CallingUserId {
            get {
                return GetAttributeValue<EntityReference>("callinguserid");
            }
        }
        
        /// <summary>
        /// <para>For given audit action, contains a string value describing the change details when corresponding IsAuditEnabled property is True</para>
        /// <para>Display Name: Change Data</para>
        /// </summary>
        [AttributeLogicalName("changedata")]
        [DisplayName("Change Data")]
        public string ChangeData {
            get {
                return GetAttributeValue<string>("changedata");
            }
        }
        
        /// <summary>
        /// <para>Date and time when the audit record was created.</para>
        /// <para>Display Name: Changed Date</para>
        /// </summary>
        [AttributeLogicalName("createdon")]
        [DisplayName("Changed Date")]
        public DateTime? CreatedOn {
            get {
                return GetAttributeValue<DateTime?>("createdon");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the record that is being audited</para>
        /// <para>Display Name: Record</para>
        /// </summary>
        [AttributeLogicalName("objectid")]
        [DisplayName("Record")]
        public EntityReference ObjectId {
            get {
                return GetAttributeValue<EntityReference>("objectid");
            }
        }
        
        /// <summary>
        /// <para>The action that causes the audit--it will be create, delete, update, upsert or archive</para>
        /// <para>Display Name: Operation</para>
        /// </summary>
        [AttributeLogicalName("operation")]
        [DisplayName("Operation")]
        public Audit_Operation? Operation {
            get {
                return GetOptionSetValue<Audit_Operation>("operation");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the object with which the record is associated.</para>
        /// <para>Display Name: Regarding</para>
        /// </summary>
        [AttributeLogicalName("regardingobjectid")]
        [DisplayName("Regarding")]
        public EntityReference RegardingObjectId {
            get {
                return GetAttributeValue<EntityReference>("regardingobjectid");
            }
            set {
                SetAttributeValue("regardingobjectid", value);
            }
        }
        
        /// <summary>
        /// <para>Time to live in seconds for audit record</para>
        /// <para>Display Name: Time To Live In Seconds</para>
        /// </summary>
        [AttributeLogicalName("timetoliveinseconds")]
        [DisplayName("Time To Live In Seconds")]
        [Range(-1, 2147483647)]
        public int? TimeToLiveInSeconds {
            get {
                return GetAttributeValue<int?>("timetoliveinseconds");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier for multiple changes that are part of a single operation; this field contains the same GUID for all the audit rows generated in a single transaction</para>
        /// <para>Display Name: Transaction Id</para>
        /// </summary>
        [AttributeLogicalName("transactionid")]
        [DisplayName("Transaction Id")]
        public Guid? TransactionId {
            get {
                return GetAttributeValue<Guid?>("transactionid");
            }
        }
        
        /// <summary>
        /// <para>Additional information associated to the user who caused the change.</para>
        /// <para>Display Name: User Info</para>
        /// </summary>
        [AttributeLogicalName("useradditionalinfo")]
        [DisplayName("User Info")]
        [MaxLength(350)]
        public string UserAdditionalInfo {
            get {
                return GetAttributeValue<string>("useradditionalinfo");
            }
            set {
                SetAttributeValue("useradditionalinfo", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the user who caused a change</para>
        /// <para>Display Name: Changed By</para>
        /// </summary>
        [AttributeLogicalName("userid")]
        [DisplayName("Changed By")]
        public EntityReference UserId {
            get {
                return GetAttributeValue<EntityReference>("userid");
            }
        }
        
        /// <summary>
        /// <para>Version number of the audit.</para>
        /// <para>Display Name: Version Number</para>
        /// </summary>
        [AttributeLogicalName("versionnumber")]
        [DisplayName("Version Number")]
        public long? VersionNumber {
            get {
                return GetAttributeValue<long?>("versionnumber");
            }
        }
        
        public static Audit Retrieve(IOrganizationService service, Guid id, params Expression<Func<Audit,object>>[] attrs) {
            return service.Retrieve(id, attrs);
        }
    }
    
    [DataContract()]
    public enum Audit_Action {
        
        [EnumMember()]
        [OptionSetMetadata("Unknown", Index=0, Lcid=1033)]
        Unknown = 0,
        
        [EnumMember()]
        [OptionSetMetadata("Create", Index=1, Lcid=1033)]
        Create = 1,
        
        [EnumMember()]
        [OptionSetMetadata("Update", Index=2, Lcid=1033)]
        Update = 2,
        
        [EnumMember()]
        [OptionSetMetadata("Delete", Index=3, Lcid=1033)]
        Delete = 3,
        
        [EnumMember()]
        [OptionSetMetadata("Activate", Index=4, Lcid=1033)]
        Activate = 4,
        
        [EnumMember()]
        [OptionSetMetadata("Deactivate", Index=5, Lcid=1033)]
        Deactivate = 5,
        
        [EnumMember()]
        [OptionSetMetadata("Upsert", Index=74, Lcid=1033)]
        Upsert = 6,
        
        [EnumMember()]
        [OptionSetMetadata("Cascade", Index=6, Lcid=1033)]
        Cascade = 11,
        
        [EnumMember()]
        [OptionSetMetadata("Merge", Index=7, Lcid=1033)]
        Merge = 12,
        
        [EnumMember()]
        [OptionSetMetadata("Assign", Index=8, Lcid=1033)]
        Assign = 13,
        
        [EnumMember()]
        [OptionSetMetadata("Share", Index=9, Lcid=1033)]
        Share = 14,
        
        [EnumMember()]
        [OptionSetMetadata("Retrieve", Index=10, Lcid=1033)]
        Retrieve = 15,
        
        [EnumMember()]
        [OptionSetMetadata("Close", Index=11, Lcid=1033)]
        Close = 16,
        
        [EnumMember()]
        [OptionSetMetadata("Cancel", Index=12, Lcid=1033)]
        Cancel = 17,
        
        [EnumMember()]
        [OptionSetMetadata("Complete", Index=13, Lcid=1033)]
        Complete = 18,
        
        [EnumMember()]
        [OptionSetMetadata("Resolve", Index=14, Lcid=1033)]
        Resolve = 20,
        
        [EnumMember()]
        [OptionSetMetadata("Reopen", Index=15, Lcid=1033)]
        Reopen = 21,
        
        [EnumMember()]
        [OptionSetMetadata("Fulfill", Index=16, Lcid=1033)]
        Fulfill = 22,
        
        [EnumMember()]
        [OptionSetMetadata("Paid", Index=17, Lcid=1033)]
        Paid = 23,
        
        [EnumMember()]
        [OptionSetMetadata("Qualify", Index=18, Lcid=1033)]
        Qualify = 24,
        
        [EnumMember()]
        [OptionSetMetadata("Disqualify", Index=19, Lcid=1033)]
        Disqualify = 25,
        
        [EnumMember()]
        [OptionSetMetadata("Submit", Index=20, Lcid=1033)]
        Submit = 26,
        
        [EnumMember()]
        [OptionSetMetadata("Reject", Index=21, Lcid=1033)]
        Reject = 27,
        
        [EnumMember()]
        [OptionSetMetadata("Approve", Index=22, Lcid=1033)]
        Approve = 28,
        
        [EnumMember()]
        [OptionSetMetadata("Invoice", Index=23, Lcid=1033)]
        Invoice = 29,
        
        [EnumMember()]
        [OptionSetMetadata("Hold", Index=24, Lcid=1033)]
        Hold = 30,
        
        [EnumMember()]
        [OptionSetMetadata("Add Member", Index=25, Lcid=1033)]
        AddMember = 31,
        
        [EnumMember()]
        [OptionSetMetadata("Remove Member", Index=26, Lcid=1033)]
        RemoveMember = 32,
        
        [EnumMember()]
        [OptionSetMetadata("Associate Entities", Index=27, Lcid=1033)]
        AssociateEntities = 33,
        
        [EnumMember()]
        [OptionSetMetadata("Disassociate Entities", Index=28, Lcid=1033)]
        DisassociateEntities = 34,
        
        [EnumMember()]
        [OptionSetMetadata("Add Members", Index=29, Lcid=1033)]
        AddMembers = 35,
        
        [EnumMember()]
        [OptionSetMetadata("Remove Members", Index=30, Lcid=1033)]
        RemoveMembers = 36,
        
        [EnumMember()]
        [OptionSetMetadata("Add Item", Index=31, Lcid=1033)]
        AddItem = 37,
        
        [EnumMember()]
        [OptionSetMetadata("Remove Item", Index=32, Lcid=1033)]
        RemoveItem = 38,
        
        [EnumMember()]
        [OptionSetMetadata("Add Substitute", Index=33, Lcid=1033)]
        AddSubstitute = 39,
        
        [EnumMember()]
        [OptionSetMetadata("Remove Substitute", Index=34, Lcid=1033)]
        RemoveSubstitute = 40,
        
        [EnumMember()]
        [OptionSetMetadata("Set State", Index=35, Lcid=1033)]
        SetState = 41,
        
        [EnumMember()]
        [OptionSetMetadata("Renew", Index=36, Lcid=1033)]
        Renew = 42,
        
        [EnumMember()]
        [OptionSetMetadata("Revise", Index=37, Lcid=1033)]
        Revise = 43,
        
        [EnumMember()]
        [OptionSetMetadata("Win", Index=38, Lcid=1033)]
        Win = 44,
        
        [EnumMember()]
        [OptionSetMetadata("Lose", Index=39, Lcid=1033)]
        Lose = 45,
        
        [EnumMember()]
        [OptionSetMetadata("Internal Processing", Index=40, Lcid=1033)]
        InternalProcessing = 46,
        
        [EnumMember()]
        [OptionSetMetadata("Reschedule", Index=41, Lcid=1033)]
        Reschedule = 47,
        
        [EnumMember()]
        [OptionSetMetadata("Modify Share", Index=42, Lcid=1033)]
        ModifyShare = 48,
        
        [EnumMember()]
        [OptionSetMetadata("Unshare", Index=43, Lcid=1033)]
        Unshare = 49,
        
        [EnumMember()]
        [OptionSetMetadata("Book", Index=44, Lcid=1033)]
        Book = 50,
        
        [EnumMember()]
        [OptionSetMetadata("Generate Quote From Opportunity", Index=45, Lcid=1033)]
        GenerateQuoteFromOpportunity = 51,
        
        [EnumMember()]
        [OptionSetMetadata("Add To Queue", Index=46, Lcid=1033)]
        AddToQueue = 52,
        
        [EnumMember()]
        [OptionSetMetadata("Assign Role To Team", Index=47, Lcid=1033)]
        AssignRoleToTeam = 53,
        
        [EnumMember()]
        [OptionSetMetadata("Remove Role From Team", Index=48, Lcid=1033)]
        RemoveRoleFromTeam = 54,
        
        [EnumMember()]
        [OptionSetMetadata("Assign Role To User", Index=49, Lcid=1033)]
        AssignRoleToUser = 55,
        
        [EnumMember()]
        [OptionSetMetadata("Remove Role From User", Index=50, Lcid=1033)]
        RemoveRoleFromUser = 56,
        
        [EnumMember()]
        [OptionSetMetadata("Add Privileges to Role", Index=51, Lcid=1033)]
        AddPrivilegestoRole = 57,
        
        [EnumMember()]
        [OptionSetMetadata("Remove Privileges From Role", Index=52, Lcid=1033)]
        RemovePrivilegesFromRole = 58,
        
        [EnumMember()]
        [OptionSetMetadata("Replace Privileges In Role", Index=53, Lcid=1033)]
        ReplacePrivilegesInRole = 59,
        
        [EnumMember()]
        [OptionSetMetadata("Import Mappings", Index=54, Lcid=1033)]
        ImportMappings = 60,
        
        [EnumMember()]
        [OptionSetMetadata("Clone", Index=55, Lcid=1033)]
        Clone = 61,
        
        [EnumMember()]
        [OptionSetMetadata("Send Direct Email", Index=56, Lcid=1033)]
        SendDirectEmail = 62,
        
        [EnumMember()]
        [OptionSetMetadata("Enabled for organization", Index=57, Lcid=1033)]
        Enabledfororganization = 63,
        
        [EnumMember()]
        [OptionSetMetadata("User Access via Web", Index=58, Lcid=1033)]
        UserAccessviaWeb = 64,
        
        [EnumMember()]
        [OptionSetMetadata("User Access via Web Services", Index=59, Lcid=1033)]
        UserAccessviaWebServices = 65,
        
        [EnumMember()]
        [OptionSetMetadata("Delete Entity", Index=60, Lcid=1033)]
        DeleteEntity = 100,
        
        [EnumMember()]
        [OptionSetMetadata("Delete Attribute", Index=61, Lcid=1033)]
        DeleteAttribute = 101,
        
        [EnumMember()]
        [OptionSetMetadata("Audit Change at Entity Level", Index=62, Lcid=1033)]
        AuditChangeatEntityLevel = 102,
        
        [EnumMember()]
        [OptionSetMetadata("Audit Change at Attribute Level", Index=63, Lcid=1033)]
        AuditChangeatAttributeLevel = 103,
        
        [EnumMember()]
        [OptionSetMetadata("Audit Change at Org Level", Index=64, Lcid=1033)]
        AuditChangeatOrgLevel = 104,
        
        [EnumMember()]
        [OptionSetMetadata("Entity Audit Started", Index=65, Lcid=1033)]
        EntityAuditStarted = 105,
        
        [EnumMember()]
        [OptionSetMetadata("Attribute Audit Started", Index=66, Lcid=1033)]
        AttributeAuditStarted = 106,
        
        [EnumMember()]
        [OptionSetMetadata("Audit Enabled", Index=67, Lcid=1033)]
        AuditEnabled = 107,
        
        [EnumMember()]
        [OptionSetMetadata("Entity Audit Stopped", Index=68, Lcid=1033)]
        EntityAuditStopped = 108,
        
        [EnumMember()]
        [OptionSetMetadata("Attribute Audit Stopped", Index=69, Lcid=1033)]
        AttributeAuditStopped = 109,
        
        [EnumMember()]
        [OptionSetMetadata("Audit Disabled", Index=70, Lcid=1033)]
        AuditDisabled = 110,
        
        [EnumMember()]
        [OptionSetMetadata("Audit Log Deletion", Index=71, Lcid=1033)]
        AuditLogDeletion = 111,
        
        [EnumMember()]
        [OptionSetMetadata("User Access Audit Started", Index=72, Lcid=1033)]
        UserAccessAuditStarted = 112,
        
        [EnumMember()]
        [OptionSetMetadata("User Access Audit Stopped", Index=73, Lcid=1033)]
        UserAccessAuditStopped = 113,
        
        [EnumMember()]
        [OptionSetMetadata("Archive", Index=75, Lcid=1033)]
        Archive = 115,
        
        [EnumMember()]
        [OptionSetMetadata("Retain", Index=76, Lcid=1033)]
        Retain = 116,
        
        [EnumMember()]
        [OptionSetMetadata("RollbackRetain", Index=77, Lcid=1033)]
        RollbackRetain = 117,
        
        [EnumMember()]
        [OptionSetMetadata("IPFirewallAcccesDenied", Index=78, Lcid=1033)]
        IPFirewallAcccesDenied = 118,
        
        [EnumMember()]
        [OptionSetMetadata("IPFirewallAcccesAllowed", Index=79, Lcid=1033)]
        IPFirewallAcccesAllowed = 119,
        
        [EnumMember()]
        [OptionSetMetadata("Restore", Index=80, Lcid=1033)]
        Restore = 120,
        
        [EnumMember()]
        [OptionSetMetadata("ApplicationBasedAccessDenied", Index=81, Lcid=1033)]
        ApplicationBasedAccessDenied = 121,
        
        [EnumMember()]
        [OptionSetMetadata("ApplicationBasedAccessAllowed", Index=82, Lcid=1033)]
        ApplicationBasedAccessAllowed = 122,
        
        [EnumMember()]
        [OptionSetMetadata("Create - AI assisted", Index=83, Lcid=1033)]
        CreateAIassisted = 123,
        
        [EnumMember()]
        [OptionSetMetadata("Update - AI assisted", Index=84, Lcid=1033)]
        UpdateAIassisted = 124,
        
        [EnumMember()]
        [OptionSetMetadata("Read Unmasked", Index=85, Lcid=1033)]
        ReadUnmasked = 125,
    }
    
    [DataContract()]
    public enum Audit_Operation {
        
        [EnumMember()]
        [OptionSetMetadata("Create", Index=0, Lcid=1033)]
        Create = 1,
        
        [EnumMember()]
        [OptionSetMetadata("Update", Index=1, Lcid=1033)]
        Update = 2,
        
        [EnumMember()]
        [OptionSetMetadata("Delete", Index=2, Lcid=1033)]
        Delete = 3,
        
        [EnumMember()]
        [OptionSetMetadata("Access", Index=3, Lcid=1033)]
        Access = 4,
        
        [EnumMember()]
        [OptionSetMetadata("Upsert", Index=4, Lcid=1033)]
        Upsert = 5,
        
        [EnumMember()]
        [OptionSetMetadata("Archive", Index=5, Lcid=1033)]
        Archive = 115,
        
        [EnumMember()]
        [OptionSetMetadata("Retain", Index=6, Lcid=1033)]
        Retain = 116,
        
        [EnumMember()]
        [OptionSetMetadata("RollbackRetain", Index=7, Lcid=1033)]
        RollbackRetain = 117,
        
        [EnumMember()]
        [OptionSetMetadata("Restore", Index=8, Lcid=1033)]
        Restore = 118,
        
        [EnumMember()]
        [OptionSetMetadata("CustomOperation", Index=9, Lcid=1033)]
        CustomOperation = 200,
    }
}
