//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;


namespace Formula81.XrmToolBox.Shared.Xrm {
    
    
    /// <summary>
    /// <para>Data equivalent to files used in Web development. Web resources provide client-side components that are used to provide custom user interface elements.</para>
    /// <para>Display Name: Web Resource</para>
    /// </summary>
    [EntityLogicalName("webresource")]
    [DebuggerDisplay("{DebuggerDisplay,nq}")]
    [DataContract()]
    public partial class WebResource : ExtendedEntity<EmptyEnum, EmptyEnum> {
        
        public const string EntityLogicalName = "webresource";
        
        public const int EntityTypeCode = 9333;
        
        public WebResource() : 
                base(EntityLogicalName) {
        }
        
        public WebResource(Guid Id) : 
                base(EntityLogicalName, Id) {
        }
        
        private string DebuggerDisplay {
            get {
                return GetDebuggerDisplay("name");
            }
        }
        
        [AttributeLogicalName("webresourceid")]
        public override Guid Id {
            get {
                return base.Id;
            }
            set {
                SetId("webresourceid", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the web resource.</para>
        /// <para>Display Name: Web Resource Identifier</para>
        /// </summary>
        [AttributeLogicalName("webresourceid")]
        [DisplayName("Web Resource Identifier")]
        public Guid? WebResourceId {
            get {
                return GetAttributeValue<Guid?>("webresourceid");
            }
            set {
                SetId("webresourceid", value);
            }
        }
        
        /// <summary>
        /// <para>Information that specifies whether this component can be deleted.</para>
        /// <para>Display Name: Can Be Deleted</para>
        /// </summary>
        [AttributeLogicalName("canbedeleted")]
        [DisplayName("Can Be Deleted")]
        public BooleanManagedProperty CanBeDeleted {
            get {
                return GetAttributeValue<BooleanManagedProperty>("canbedeleted");
            }
            set {
                SetAttributeValue("canbedeleted", value);
            }
        }
        
        /// <summary>
        /// <para>For internal use only.</para>
        /// <para>Display Name: Component State</para>
        /// </summary>
        [AttributeLogicalName("componentstate")]
        [DisplayName("Component State")]
        public componentstate? ComponentState {
            get {
                return GetOptionSetValue<componentstate>("componentstate");
            }
        }
        
        /// <summary>
        /// <para>Bytes of the web resource, in Base64 format.</para>
        /// </summary>
        [AttributeLogicalName("content")]
        [MaxLength(1073741823)]
        public string Content {
            get {
                return GetAttributeValue<string>("content");
            }
            set {
                SetAttributeValue("content", value);
            }
        }
        
        /// <summary>
        /// <para>Json representation of the content of the resource.</para>
        /// </summary>
        [AttributeLogicalName("contentjson")]
        public string ContentJson {
            get {
                return GetAttributeValue<string>("contentjson");
            }
            set {
                SetAttributeValue("contentjson", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the user who created the web resource.</para>
        /// <para>Display Name: Created By</para>
        /// </summary>
        [AttributeLogicalName("createdby")]
        [DisplayName("Created By")]
        public EntityReference CreatedBy {
            get {
                return GetAttributeValue<EntityReference>("createdby");
            }
        }
        
        /// <summary>
        /// <para>Date and time when the web resource was created.</para>
        /// <para>Display Name: Created On</para>
        /// </summary>
        [AttributeLogicalName("createdon")]
        [DisplayName("Created On")]
        public DateTime? CreatedOn {
            get {
                return GetAttributeValue<DateTime?>("createdon");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the delegate user who created the web resource.</para>
        /// <para>Display Name: Created By (Delegate)</para>
        /// </summary>
        [AttributeLogicalName("createdonbehalfby")]
        [DisplayName("Created By (Delegate)")]
        public EntityReference CreatedOnBehalfBy {
            get {
                return GetAttributeValue<EntityReference>("createdonbehalfby");
            }
        }
        
        /// <summary>
        /// <para>For internal use only.</para>
        /// <para>Display Name: DependencyXML</para>
        /// </summary>
        [AttributeLogicalName("dependencyxml")]
        [DisplayName("DependencyXML")]
        public string DependencyXml {
            get {
                return GetAttributeValue<string>("dependencyxml");
            }
            set {
                SetAttributeValue("dependencyxml", value);
            }
        }
        
        /// <summary>
        /// <para>Description of the web resource.</para>
        /// <para>Display Name: Description</para>
        /// </summary>
        [AttributeLogicalName("description")]
        [DisplayName("Description")]
        public string Description {
            get {
                return GetAttributeValue<string>("description");
            }
            set {
                SetAttributeValue("description", value);
            }
        }
        
        /// <summary>
        /// <para>Display name of the web resource.</para>
        /// <para>Display Name: Display Name</para>
        /// </summary>
        [AttributeLogicalName("displayname")]
        [DisplayName("Display Name")]
        [MaxLength(200)]
        public string DisplayName {
            get {
                return GetAttributeValue<string>("displayname");
            }
            set {
                SetAttributeValue("displayname", value);
            }
        }
        
        /// <summary>
        /// <para>Version in which the form is introduced.</para>
        /// <para>Display Name: Introduced Version</para>
        /// </summary>
        [AttributeLogicalName("introducedversion")]
        [DisplayName("Introduced Version")]
        [MaxLength(48)]
        public string IntroducedVersion {
            get {
                return GetAttributeValue<string>("introducedversion");
            }
            set {
                SetAttributeValue("introducedversion", value);
            }
        }
        
        /// <summary>
        /// <para>Information that specifies whether this web resource is available for mobile client in offline mode.</para>
        /// <para>Display Name: Is Available For Mobile Offline</para>
        /// </summary>
        [AttributeLogicalName("isavailableformobileoffline")]
        [DisplayName("Is Available For Mobile Offline")]
        public bool? IsAvailableForMobileOffline {
            get {
                return GetAttributeValue<bool?>("isavailableformobileoffline");
            }
            set {
                SetAttributeValue("isavailableformobileoffline", value);
            }
        }
        
        /// <summary>
        /// <para>Information that specifies whether this component can be customized.</para>
        /// <para>Display Name: Customizable</para>
        /// </summary>
        [AttributeLogicalName("iscustomizable")]
        [DisplayName("Customizable")]
        public BooleanManagedProperty IsCustomizable {
            get {
                return GetAttributeValue<BooleanManagedProperty>("iscustomizable");
            }
            set {
                SetAttributeValue("iscustomizable", value);
            }
        }
        
        /// <summary>
        /// <para>Information that specifies whether this web resource is enabled for mobile client.</para>
        /// <para>Display Name: Is Enabled For Mobile Client</para>
        /// </summary>
        [AttributeLogicalName("isenabledformobileclient")]
        [DisplayName("Is Enabled For Mobile Client")]
        public bool? IsEnabledForMobileClient {
            get {
                return GetAttributeValue<bool?>("isenabledformobileclient");
            }
            set {
                SetAttributeValue("isenabledformobileclient", value);
            }
        }
        
        /// <summary>
        /// <para>Information that specifies whether this component should be hidden.</para>
        /// <para>Display Name: Hidden</para>
        /// </summary>
        [AttributeLogicalName("ishidden")]
        [DisplayName("Hidden")]
        public BooleanManagedProperty IsHidden {
            get {
                return GetAttributeValue<BooleanManagedProperty>("ishidden");
            }
            set {
                SetAttributeValue("ishidden", value);
            }
        }
        
        [AttributeLogicalName("ismanaged")]
        public bool? IsManaged {
            get {
                return GetAttributeValue<bool?>("ismanaged");
            }
        }
        
        /// <summary>
        /// <para>Language of the web resource.</para>
        /// <para>Display Name: Language</para>
        /// </summary>
        [AttributeLogicalName("languagecode")]
        [DisplayName("Language")]
        [Range(0, 2147483647)]
        public int? LanguageCode {
            get {
                return GetAttributeValue<int?>("languagecode");
            }
            set {
                SetAttributeValue("languagecode", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the user who last modified the web resource.</para>
        /// <para>Display Name: Modified By</para>
        /// </summary>
        [AttributeLogicalName("modifiedby")]
        [DisplayName("Modified By")]
        public EntityReference ModifiedBy {
            get {
                return GetAttributeValue<EntityReference>("modifiedby");
            }
        }
        
        /// <summary>
        /// <para>Date and time when the web resource was last modified.</para>
        /// <para>Display Name: Modified On</para>
        /// </summary>
        [AttributeLogicalName("modifiedon")]
        [DisplayName("Modified On")]
        public DateTime? ModifiedOn {
            get {
                return GetAttributeValue<DateTime?>("modifiedon");
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the delegate user who modified the web resource.</para>
        /// <para>Display Name: Created By (Delegate)</para>
        /// </summary>
        [AttributeLogicalName("modifiedonbehalfby")]
        [DisplayName("Created By (Delegate)")]
        public EntityReference ModifiedOnBehalfBy {
            get {
                return GetAttributeValue<EntityReference>("modifiedonbehalfby");
            }
        }
        
        /// <summary>
        /// <para>Name of the web resource.</para>
        /// <para>Display Name: Name</para>
        /// </summary>
        [AttributeLogicalName("name")]
        [DisplayName("Name")]
        [MaxLength(256)]
        public string Name {
            get {
                return GetAttributeValue<string>("name");
            }
            set {
                SetAttributeValue("name", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the organization associated with the web resource.</para>
        /// <para>Display Name: Organization</para>
        /// </summary>
        [AttributeLogicalName("organizationid")]
        [DisplayName("Organization")]
        public EntityReference OrganizationId {
            get {
                return GetAttributeValue<EntityReference>("organizationid");
            }
        }
        
        /// <summary>
        /// <para>For internal use only.</para>
        /// <para>Display Name: Record Overwrite Time</para>
        /// </summary>
        [AttributeLogicalName("overwritetime")]
        [DisplayName("Record Overwrite Time")]
        public DateTime? OverwriteTime {
            get {
                return GetAttributeValue<DateTime?>("overwritetime");
            }
        }
        
        /// <summary>
        /// <para>Name of the web resource.</para>
        /// <para>Display Name: Name</para>
        /// </summary>
        [AttributeLogicalName("name")]
        [DisplayName("Name")]
        [MaxLength(256)]
        public string PrimaryNameField {
            get {
                return GetAttributeValue<string>("name");
            }
            set {
                SetAttributeValue("name", value);
            }
        }
        
        /// <summary>
        /// <para>Silverlight runtime version number required by a silverlight web resource.</para>
        /// <para>Display Name: Silverlight Version</para>
        /// </summary>
        [AttributeLogicalName("silverlightversion")]
        [DisplayName("Silverlight Version")]
        [MaxLength(20)]
        public string SilverlightVersion {
            get {
                return GetAttributeValue<string>("silverlightversion");
            }
            set {
                SetAttributeValue("silverlightversion", value);
            }
        }
        
        /// <summary>
        /// <para>Unique identifier of the associated solution.</para>
        /// <para>Display Name: Solution</para>
        /// </summary>
        [AttributeLogicalName("solutionid")]
        [DisplayName("Solution")]
        public Guid? SolutionId {
            get {
                return GetAttributeValue<Guid?>("solutionid");
            }
        }
        
        [AttributeLogicalName("versionnumber")]
        public long? VersionNumber {
            get {
                return GetAttributeValue<long?>("versionnumber");
            }
        }
        
        /// <summary>
        /// <para>For internal use only.</para>
        /// </summary>
        [AttributeLogicalName("webresourceidunique")]
        public Guid? WebResourceIdUnique {
            get {
                return GetAttributeValue<Guid?>("webresourceidunique");
            }
        }
        
        /// <summary>
        /// <para>Drop-down list for selecting the type of the web resource.</para>
        /// <para>Display Name: Type</para>
        /// </summary>
        [AttributeLogicalName("webresourcetype")]
        [DisplayName("Type")]
        public WebResource_WebResourceType? WebResourceType {
            get {
                return GetOptionSetValue<WebResource_WebResourceType>("webresourcetype");
            }
            set {
                SetOptionSetValue("webresourcetype", value);
            }
        }
        
        public static WebResource Retrieve(IOrganizationService service, Guid id, params Expression<Func<WebResource,object>>[] attrs) {
            return service.Retrieve(id, attrs);
        }
    }
    
    [DataContract()]
    public enum WebResource_WebResourceType {
        
        [EnumMember()]
        [OptionSetMetadata("Webpage (HTML)", Index=0, Lcid=1033)]
        WebpageHTML = 1,
        
        [EnumMember()]
        [OptionSetMetadata("Style Sheet (CSS)", Index=1, Lcid=1033)]
        StyleSheetCSS = 2,
        
        [EnumMember()]
        [OptionSetMetadata("Script (JScript)", Index=2, Lcid=1033)]
        ScriptJScript = 3,
        
        [EnumMember()]
        [OptionSetMetadata("Data (XML)", Index=3, Lcid=1033)]
        DataXML = 4,
        
        [EnumMember()]
        [OptionSetMetadata("PNG format", Index=4, Lcid=1033)]
        PNGformat = 5,
        
        [EnumMember()]
        [OptionSetMetadata("JPG format", Index=5, Lcid=1033)]
        JPGformat = 6,
        
        [EnumMember()]
        [OptionSetMetadata("GIF format", Index=6, Lcid=1033)]
        GIFformat = 7,
        
        [EnumMember()]
        [OptionSetMetadata("Silverlight (XAP)", Index=7, Lcid=1033)]
        SilverlightXAP = 8,
        
        [EnumMember()]
        [OptionSetMetadata("Style Sheet (XSL)", Index=8, Lcid=1033)]
        StyleSheetXSL = 9,
        
        [EnumMember()]
        [OptionSetMetadata("ICO format", Index=9, Lcid=1033)]
        ICOformat = 10,
        
        [EnumMember()]
        [OptionSetMetadata("Vector format (SVG)", Index=10, Lcid=1033)]
        VectorformatSVG = 11,
        
        [EnumMember()]
        [OptionSetMetadata("String (RESX)", Index=11, Lcid=1033)]
        StringRESX = 12,
    }
}
